name: Add comment from file
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'help wanted'
    runs-on: self-hosted
    permissions:
      issues: write
    outputs:
      content: ${{ steps.fileid.outputs.content }}
    steps:
      - name: Setup Python 3.x environment on the runner
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Git install
        run: |
            (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update > /dev/null 2>&1 \
            && sudo apt install gh -y > /dev/null 2>&1
            sudo apt install git -y > /dev/null 2>&1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create file
        run: |
            python3 file.py
            whereis gh
      #- name: Read file
      #  id: fileid
      #  run: |
      #      echo "content=`cat file.md`" >> $GITHUB_OUTPUT
      - name: Add comment
        run: cat file.md | gh issue comment "$NUMBER" --body "$BODY" -
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          #GH_REPO: "github.kyndryl.net/michal-fityka/terraform-automation"
          NUMBER: ${{ github.event.issue.number }}
          #BODY: >
          #    ${{ steps.fileid.outputs.content }}
