name: Add comment from file
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'help wanted'
    runs-on: self-hosted
    permissions:
      issues: write
    steps:
      - name: Setup Python 3.x environment on the runner
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Create file
        run: |
            python3 file.py
      - name: Read file
        id: fileid
        run: >-
            echo "::set-output name=FILE_CONTENT::$(
            cat file.md)"
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          #GH_REPO: "github.kyndryl.net/michal-fityka/terraform-automation"
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is available for anyone to work on.
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:
